# Generated by Django 3.0.5 on 2020-08-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
    ]
